### ISSUE TITLE
Temperature transform

### ISSUE THREAD

**Issue by EvanYathon** [UBC-MDS/DSCI_522_Capital_Bikeshare_Analysis#14]
From what I'm seeing in the EDA plots and also what Mike said today in lecture, it sounds like we can leave the temperature as is.
For future reference: the temperature was normalized, Mike said that normalized values will have the same output in decision trees.

**Comment by Mikeymice** [comment]
sounds good. another thing just came to my mind is that when you do EDA with the cleaned data you can probably omit all the rows that has rental_type as `both` because it is just a combination of casual and registered.

**Comment by EvanYathon** [comment]
I was thinking that we would be doing the learning/predictions solely on the `both` data.  Were you thinking that we would do it separately on registered and casual users?

**Comment by Mikeymice** [comment]
if we want to know the effect of rental type on number of rental per day we are looking at the features of either casual and registered. for the row with rental type both the rental number is simply adding casual with registered. i don't know if that will be a distraction. In a sense, we will probably get the conclusion that rental type both will always have more rental number which is meaningless because `both` = `registered` + `causal` always

**Comment by Mikeymice** [comment]
unless we just don't use rental_type as feature when we do EDA and analysis, and only using rows with `both` rental type?

**Comment by EvanYathon** [comment]
Yes, that's what I was thinking, to not use `rental_type` as a feature when learning.  To me `rental_type` really isn't a feature such as `weather` or `temp` that would affect the amount of riders per day.  It is just a different subset of the total riders on each day.  I would be more comfortable not using `rental_type` as a feature

**Comment by Mikeymice** [comment]
i agree with you. i think it is the best if we just just `both` and omit the rental_type column when EDA and doing decision tree
